第五阶段/DEVWEB/for_django/Scripts/mysite1/aaa/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
     url(r'^$',views.index,name='index'),
     url(r'(?P<question_id>\d+)/$',views.detail,name='detail'),
     url(r'(?P<question_id>\d+)/result/$',views.result,name='result'),
     url(r'(?P<question_id>\d+)/vote/$',views.vote,name='vote'),
]

第五阶段/DEVWEB/for_django/Scripts/mysite1/mysite1/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^aaa/', include('aaa.urls')),
]

第五阶段/DEVWEB/for_django/Scripts/mysite1/aaa/models.py
from django.db import models
from django.db import models
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    publish_date=models.DateTimeField('date published')
    date_hierarchy = 'publish_date'
    search_fields = ('question_text',)
    ordering = ('publish_date', 'question_text')
    def __str__(self):
        return self.question_text
class Choice(models.Model):
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    list_display = ('choice_text', 'votes', 'question')
    raw_id_fields = ('question',)
    def __str__(self):
        return self.choice_text
# Create your models here.

第五阶段/DEVWEB/for_django/Scripts/mysite1/aaa/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404,redirect
from .models import Question,Choice
# def index(request):
#     return HttpResponse('<h1>polls ok </h1>')
def index(request):
    questions=Question.objects.all() #获取所有的问题
    #render用于向用户返回一个网页（模版），字典是传给网页的参数
    return render(request,'aaa/index.html',{'question':questions})
def detail(request,question_id):
    # question=Question.objects.get(id=question_id)
    question=get_object_or_404(Question,id=question_id)
    return render(request,'aaa/detail.html',{'question':question})
def result(request,question_id):
    question=get_object_or_404(Question,id=question_id)
    return render(request, 'aaa/result.html', {'question': question})
def vote(request,question_id):
    choice_id=request.POST.get('c.id')
    c=get_object_or_404(Choice,id=choice_id)
    c.votes += 1
    c.save()
    return  redirect('result',question_id=question_id)

第五阶段/DEVWEB/for_django/Scripts/mysite1/aaa/templates/aaa/detail.html
{% extends 'base.html' %}
{% block title %}投票详情页{% endblock %}
{% block content %}
         <form action="{% url 'vote' question_id=question.id %}" method="post">
        <p>{{question.question_text}}</p>
        {% for c in question.choice_set.all %}
            <label>
                <input type="radio" name="c.id" value="{{c.id}}">{{c.choice_text}}
            </label>
        {% endfor %}
        <input type="submit" value="提交">
    </form>
    <a href="{% url 'index' %}">返回首页</a>
{% endblock %}

第五阶段/DEVWEB/for_django/Scripts/mysite1/aaa/templates/aaa/index.html
{% extends 'base.html' %}
{% block title %}aaa主页{% endblock %}
{% block content %}
     <ul>
        {% for q in question %}
           <!--<li><a href="http://127.0.0.1/aaa/{{q.id}}">{{q.question_text}}</a>{{q.publish_date}}</li>-->
            <li><a href="{% url 'detail' question_id=q.id %}">{{q.question_text}}</a>{{q.publish_date}}</li>
        {% endfor %}
    </ul>
{% endblock %}

第五阶段/DEVWEB/for_django/Scripts/mysite1/aaa/templates/aaa/result.html
{% extends 'base.html' %}
{% block title %}投票结果{% endblock %}
{% block content %}
<table class="table table-striped table-hover">
    <tr class="info">
        <td colspan="2">{{question.question_text}}</td>
    </tr>
    {% for c in question.choice_set.all %}
        <tr>
            <td>{{c.choice_text}}</td>
            <td>票数：{{c.votes}}</td>
        </tr>
    {% endfor %}
</table>
<a href="{% url 'index' %}">返回首页</a>
{% endblock %}

第五阶段/DEVWEB/for_django/Scripts/mysite1/aaa/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="container h3">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>